"""
Alert data models for VoxSentinel.

Defines the Pydantic models for alert events generated by keyword matches,
sentiment escalations, compliance violations, and intent detections.
Includes ``KeywordMatchEvent`` and ``SentimentEvent`` intermediate events
as well as the persisted ``Alert`` with delivery-status tracking.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    """Return the current UTC datetime."""
    return datetime.now(timezone.utc)


class AlertType(str, enum.Enum):
    """Category of alert trigger."""

    KEYWORD = "keyword"
    SENTIMENT = "sentiment"
    COMPLIANCE = "compliance"
    INTENT = "intent"


class Severity(str, enum.Enum):
    """Alert severity level."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MatchType(str, enum.Enum):
    """How a keyword/rule was matched."""

    EXACT = "exact"
    FUZZY = "fuzzy"
    REGEX = "regex"
    SENTIMENT_THRESHOLD = "sentiment_threshold"
    INTENT = "intent"


# ── Intermediate event models (not persisted directly) ──


class KeywordMatchEvent(BaseModel):
    """Event emitted by the NLP keyword engine when a rule matches.

    Attributes:
        keyword: The keyword or phrase that matched.
        match_type: Matching strategy used.
        similarity_score: Fuzzy similarity score (None for exact/regex).
        matched_text: The actual text that matched.
        stream_id: Stream where the match occurred.
        session_id: Active session UUID.
        timestamp: When the match was detected.
        speaker_id: Speaker label (if available).
        surrounding_context: ±5 s of surrounding transcript.
    """

    model_config = {"from_attributes": True}

    keyword: str = Field(..., description="Keyword or phrase that matched.")
    match_type: MatchType = Field(..., description="Matching strategy used.")
    similarity_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Fuzzy similarity score.",
    )
    matched_text: str = Field(..., description="Actual text that matched.")
    stream_id: UUID = Field(..., description="Stream where match occurred.")
    session_id: UUID = Field(..., description="Active session UUID.")
    timestamp: datetime = Field(default_factory=_utc_now, description="Detection timestamp.")
    speaker_id: str | None = Field(default=None, description="Speaker label.")
    surrounding_context: str = Field(
        default="",
        description="±5 s of surrounding transcript.",
    )


class SentimentEvent(BaseModel):
    """Event emitted when a sentiment threshold is breached.

    Attributes:
        stream_id: Stream where the sentiment was detected.
        session_id: Active session UUID.
        speaker_id: Speaker label (if available).
        timestamp: When the sentiment was measured.
        sentiment_label: Classification result (positive/neutral/negative).
        sentiment_score: Confidence score.
        intent_label: Optional detected intent.
        intent_confidence: Intent classification confidence.
    """

    model_config = {"from_attributes": True}

    stream_id: UUID = Field(..., description="Stream UUID.")
    session_id: UUID = Field(..., description="Session UUID.")
    speaker_id: str | None = Field(default=None, description="Speaker label.")
    timestamp: datetime = Field(default_factory=_utc_now, description="Measurement timestamp.")
    sentiment_label: str = Field(..., max_length=20, description="positive/neutral/negative.")
    sentiment_score: float = Field(..., ge=0.0, le=1.0, description="Sentiment confidence.")
    intent_label: str | None = Field(default=None, description="Detected intent label.")
    intent_confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Intent confidence.",
    )


# ── Persisted alert model ──


class Alert(BaseModel):
    """A persisted alert record.

    Attributes:
        alert_id: Unique identifier.
        session_id: Parent session UUID.
        stream_id: Parent stream UUID.
        segment_id: Triggering transcript segment UUID.
        alert_type: Alert category.
        severity: Severity level.
        matched_rule: Keyword/rule that triggered the alert.
        match_type: How it was matched.
        similarity_score: Fuzzy match score (None for exact/regex).
        matched_text: Text that triggered the match.
        surrounding_context: ±5 s of surrounding transcript.
        speaker_id: Speaker who triggered the alert.
        channel: Audio channel (if multi-channel).
        sentiment_scores: Sentiment state at time of alert.
        asr_backend_used: ASR backend at time of alert.
        delivered_to: Channels the alert was sent to.
        delivery_status: Per-channel delivery status.
        deduplicated: Whether this alert was suppressed by dedup.
        created_at: Alert creation timestamp (UTC).
    """

    model_config = {"from_attributes": True}

    alert_id: UUID = Field(default_factory=uuid4, description="Unique identifier.")
    session_id: UUID = Field(..., description="Parent session UUID.")
    stream_id: UUID = Field(..., description="Parent stream UUID.")
    segment_id: UUID | None = Field(default=None, description="Triggering segment UUID.")
    alert_type: AlertType = Field(..., description="Alert category.")
    severity: Severity = Field(..., description="Severity level.")
    matched_rule: str = Field(
        default="",
        max_length=255,
        description="Keyword/rule that triggered.",
    )
    match_type: MatchType = Field(..., description="How it was matched.")
    similarity_score: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Fuzzy match score.",
    )
    matched_text: str = Field(default="", description="Text that triggered the match.")
    surrounding_context: str = Field(
        default="",
        description="±5 s of surrounding transcript.",
    )
    speaker_id: str | None = Field(
        default=None,
        max_length=100,
        description="Speaker who triggered the alert.",
    )
    channel: str | None = Field(
        default=None,
        max_length=50,
        description="Audio channel (if multi-channel).",
    )
    sentiment_scores: dict[str, float] | None = Field(
        default=None,
        description="Sentiment state at time of alert.",
    )
    asr_backend_used: str | None = Field(
        default=None,
        max_length=100,
        description="ASR backend at time of alert.",
    )
    delivered_to: list[str] = Field(
        default_factory=list,
        description="Channels the alert was sent to.",
    )
    delivery_status: dict[str, str] = Field(
        default_factory=dict,
        description="Per-channel delivery status.",
    )
    deduplicated: bool = Field(
        default=False,
        description="Whether this alert was suppressed by dedup.",
    )
    created_at: datetime = Field(
        default_factory=_utc_now,
        description="Alert creation timestamp (UTC).",
    )
