"""
Alert data model for VoxSentinel.

Defines the Pydantic model for alert events generated by keyword matches,
sentiment escalations, compliance violations, and intent detections.
Includes delivery status tracking across multiple channels.
"""

from __future__ import annotations

from pydantic import BaseModel
